apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: casbin-webhook-svc
  labels:
    app: casbin-webhook-svc
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: casbin-webhook
