apiVersion: "auth.casbin.org/v1"
kind: CasbinModel
metadata:
  name: image-digest
spec:
  enabled: true
  modelText: |
    [request_definition]
    r =  obj

    [policy_definition]
    p =  obj,eft

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = ${NAMESPACE} == "default" && ${RESOURCE} =="deployments" && \
    matchRegex(accessWithWildcard(${OBJECT}.Spec.Template.Spec.Containers , "*", "Image") , p.obj) || \
    ${RESOURCE} !="deployments"
