apiVersion: "auth.casbin.org/v1"
kind: CasbinModel
metadata:
  name: disallowed-tag
spec:
  enabled: true
  modelText: |
    [request_definition]
    r =  obj

    [policy_definition]
    p =  obj,eft

    [policy_effect]
    e = !some(where (p.eft == deny))

    [matchers]
    m = ${NAMESPACE} == "default" && ${RESOURCE} =="deployments" && \
    contain(split(accessWithWildcard(${OBJECT}.Spec.Template.Spec.Containers , "*", "Image"),":",1) , p.obj)
