apiVersion: "auth.casbin.org/v1"
kind: CasbinModel
metadata:
  name: https-only
spec:
  enabled: true
  modelText: |
    [request_definition]
    r =  obj

    [policy_definition]
    p =  obj,eft

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = ${NAMESPACE} == "default" && ${RESOURCE} =="ingresses" && \
    access(${OBJECT} , "Annotations", "kubernetes.io/ingress.allow-http") == "false" &&\
    parseFloat(len(${OBJECT}.Spec.TLS)) > 0 || \
    ${RESOURCE} !="ingresses"
