apiVersion: "auth.casbin.org/v1"
kind: CasbinModel
metadata:
  name: external-ip
spec:
  enabled: true
  modelText: |
    [request_definition]
    r =  obj

    [policy_definition]
    p =  obj,eft

    [policy_effect]
    e = !some(where (p.eft == deny))

    [matchers]
    m = ${NAMESPACE} == "default" && ${RESOURCE} =="services" && \
    contain(accessWithWildcard(${OBJECT}.Spec.ExternalIPs , "*") , p.obj)
